bind = "unix:/tmp/uvicorn.sock"
# wsgi_app = "config.wsgi:application"
backlog = 2048
workers = 4
worker_class = "uvicorn.workers.UvicornWorker"
worker_connections = 1000
reload = True
timeout = 30
keepalive = 3
spew = False
daemon = False
pidfile = None
umask = 0
user = "deploy"
group = "deploy"
tmp_upload_dir = None
gunicorn_log = True
access_log_format = '%(asctime)s 시ㅣㅣㅣㅣㅣㅣㅣ이발 [%(levelname)s] %(name)s: %(message)s'
accesslog = "/var/log/uvicorn/access.log"
errorlog = "/var/log/uvicorn/error.log"
loglevel = "critical"
proc_name = None